# Generated by Django 4.2.4 on 2025-01-28 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=100)),
                ('allergen_info', models.TextField(blank=True)),
                ('minimum_required_quantity', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('category', models.CharField(choices=[('oils', 'Oils'), ('dairy', 'Dairy'), ('wines', 'Wines'), ('meats', 'Meats'), ('fish', 'Fish'), ('frozen', 'Frozen')], max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.FloatField()),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_required_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='food.ingredient')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_entries', to='food.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='ingredients',
            field=models.ManyToManyField(related_name='inventory_entries', through='food.InventoryIngredient', to='food.ingredient'),
        ),
    ]
