# Generated by Django 4.2.4 on 2025-01-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='management.restaurant'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='management.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'restaurant')},
        ),
    ]
