# Generated by Django 4.2.4 on 2025-01-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryingredient',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ingredients', to='management.restaurant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='management.restaurant'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='management.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryingredient',
            unique_together={('inventory', 'ingredient', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product_name', 'restaurant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'restaurant')},
        ),
    ]
