# Generated by Django 4.2.4 on 2023-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_inventory_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
