# Generated by Django 4.2.4 on 2023-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_inventory_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
