# Generated by Django 4.2.4 on 2023-12-07 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('preferred_dishes', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
