# Generated by Django 4.2.4 on 2023-12-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cod',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='identification',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
