# Generated by Django 4.2.4 on 2023-12-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_dish_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_vegetarian',
        ),
    ]
