# Generated by Django 4.2.4 on 2023-12-07 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_dish_category_remove_dish_is_gluten_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='net_sale_price',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_cost',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='tax_percentage',
            field=models.FloatField(default=1, help_text='Enter tax percentage (e.g., 10 for 10%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
