# Generated by Django 4.2.4 on 2023-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_inventory_category_inventory_code_inventory_quantity_and_more'),
        ('management', '0005_dish_net_sale_price_dish_profit_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='food.inventory'),
        ),
    ]
