# Generated by Django 4.2.4 on 2023-12-07 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Enter tax percentage (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
