# Generated by Django 4.2.4 on 2023-12-07 18:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_dish_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter tax percentage (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
